# -*- coding: utf-8 -*-
"""Corn Seeds Detection Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PkP-pECPDMsTvbLu91ACLtFRVY0b9a1
"""

import tensorflow as tf

import keras

from keras._tf_keras.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

!unzip "/usr/local/cornseeds/training_set.zip" -d "/usr/local/cornseeds/training_set"

training_set1 = datagen.flow_from_directory(
    '/usr/local/cornseeds/training_set',
    target_size=(64, 64),
    batch_size=32,
    class_mode='binary'
)

training_datagenerator1 = ImageDataGenerator(rescale = 1./255)

testing_set1 = training_datagenerator1.flow_from_directory(
    '/usr/local/cornseeds/training_set',
    target_size=(64, 64),
    batch_size=32,
    class_mode='binary'
)

cnn_process1 = tf.keras.models.Sequential()

"""# FIRST LAYER"""

cnn_process1.add(
    tf.keras.layers.Conv2D(
        filters=32,
        kernel_size=3,
        activation='relu',
        input_shape=[64, 64, 3]
    )
)

cnn_process1.add(
    tf.keras.layers.MaxPool2D(
        pool_size = 2,
        strides = 2
    )
)

"""# SECOND LAYER"""

cnn_process1.add(
    tf.keras.layers.Conv2D(
        filters=32,
        kernel_size=3,
        activation='relu',
    )
)
cnn_process1.add(
    tf.keras.layers.MaxPool2D(
        pool_size = 2,
        strides = 2
    )
)

cnn_process1.add(tf.keras.layers.Flatten())

cnn_process1.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn_process1.add(tf.keras.layers.Dropout(0.5))

cnn_process1.add(tf.keras.layers.Dense(units=128, activation='sigmond'))

cnn_process1.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

cnn_process1.fit(x=training_set1, validation_data=testing_set1, epochs=20)

"""* PROCESSING"""

import numpy as np
from keras.preprocessing import image

test_images1 = image.load_img('usr/local/cornseeds/testing_set/healthycorn/healthy_corn_0001.jpg', target_size=(64, 64))
test_images1 = image.img_to_array(test_images1)
test_images1 = np.expand_dims(test_images1, axis=0)
result1 = cnn_process1.predict(test_images1)
training_set1.class_indices
if result1[0][0] == 1:
    prediction = 'healthy'
else:
    prediction = 'unhealthy'
print(prediction)